//! Contains types related to entity components.

use super::{packed::PackedStorage, ComponentStorage};
use std::{
    any::TypeId,
    fmt::{Display, Formatter},
    hash::Hasher,
};

/// A unique ID for a component type.
#[derive(Copy, Clone, Debug, Eq, PartialOrd, Ord)]
pub struct ComponentTypeId {
    /// unique type id generated by rust
    pub type_id: TypeId,
    /// unique external type id generated outside rust
    pub ext_type_id: Option<u32>,
    /// string representation of component
    #[cfg(debug_assertions)]
    pub name: &'static str,
}

impl ComponentTypeId {
    /// Constructs the component type ID for the given component type.
    pub fn of<T: Component>() -> Self {
        Self {
            type_id: TypeId::of::<T>(),
            ext_type_id: None,
            #[cfg(debug_assertions)]
            name: std::any::type_name::<T>(),
        }
    }

    /// Returns the internal TypeID of the component.
    pub fn type_id(&self) -> TypeId {
        self.type_id
    }
}

impl std::hash::Hash for ComponentTypeId {
    fn hash<H: Hasher>(&self, state: &mut H) {
        self.type_id.hash(state);
    }
}

impl PartialEq for ComponentTypeId {
    fn eq(&self, other: &Self) -> bool {
       
        if let Some(ext_id) = self.ext_type_id {
            if let Some(other_ext_id) = other.ext_type_id {
                return self.type_id.eq(&other.type_id) && ext_id.eq(&other_ext_id)
            }

            return false
        }
        
        return self.type_id.eq(&other.type_id)
    }
}

impl Display for ComponentTypeId {
    #[cfg(debug_assertions)]
    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.name)
    }

    #[cfg(not(debug_assertions))]
    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        write!(f, "{:?}", self.type_id)
    }
}

/// A marker trait for all types which can be attached to an entity.
///
/// This trait has a blanket impl for all applicable types.
pub trait Component: 'static + Sized + Send + Sync {
    /// The storage type required to hold all instances of this component in a world.
    type Storage: for<'a> ComponentStorage<'a, Self>;
}

impl<T: 'static + Sized + Send + Sync> Component for T {
    type Storage = PackedStorage<T>;
}
